### ISSUE TITLE
Shop_SetClientItemTimeleft

### ISSUE THREAD

**Issue by R1KO** [R1KO/Shop-Core#1]
**native bool:Shop_SetClientItemTimeleft(client, ItemId:item_id, timeleft);**
Если timeleft = 0, то у пользователя остаётся 0 секунд на предмете, и при использовании предмета, он пропадает.
Судя документации API по шопу, если timeleft = 0, то у пользователя предмет навсегда. Но в результате - это не так.
В общем баг заключается в том, что в базе есть 2 поля, отвечающих за время предмета. И один из них обнуляется, а второй, нет. По результату этих двух полей, а именно их разница, высчитывается оставшееся время для предмета. И результат таков что разница  выдает 0 следовательно предмет приобретает свойство времени не "навсегда", а на "0 секунд".

**Comment by TiBarification** [comment]
(c) TiBarification ;)
