### ISSUE TITLE
"Съезжают" категории в меню шопа.

### ISSUE THREAD

**Issue by samoletik1337** [R1KO/Shop-Core#16]
При нажатии на категорию "[ Дополнительно ]", открывается любая иная категория , но не она, при нажатии на 1 первую категорию всегда открывается одна и та же, но если убрать любой плагин создающий какую-либо категорию , то при нажатии на первую категорию "[ Дополнительно ]" открывается уже другая категория. Пример ниже:
Жму на [ Дополнительно ]
![image](https://user-images.githubusercontent.com/28659564/33219251-231f0e6e-d163-11e7-98dd-32c656ab100e.png)
Открывается категория "Аура(партикли)"
![image](https://user-images.githubusercontent.com/28659564/33219458-1b04d870-d164-11e7-9181-0ac230072814.png)
Затем выхожу из категории и жму на" Аура(партикли)"
![image](https://user-images.githubusercontent.com/28659564/33219463-1fc461be-d164-11e7-9156-889aad13c0f4.png)
Открывается категория [ Дополнительно ].

Последняя версия шопа из ветки dev

**Comment by CrazyHackGUT** [comment]
Экспериментальным путём выявлено, что проблема связана с сортировкой предметов.
Если никакой сортировки нет, баг не проявляется.
Если хотя бы один элемент в сортировке есть, то он проявится.

**Comment by R1KO** [comment]
https://github.com/R1KO/Shop-Core/commit/a1ecf071cb9b73602b68d4451f5a4d29df8ece68
