### ISSUE TITLE
 [Shop] Your data is being loaded!

### ISSUE THREAD

**Issue by SSadistic** [R1KO/Shop-Core#17]
The plugin keeps saying  [Shop] Your data is being loaded! when I type !shop

What's in database.cfg:
	"shop"
	{
		"driver"        "mysql"
		"host"				"IP"
		"database"			"DB"
		"user"				"USER"
		"pass"				"Pass"
		"port"			"3306"
	}

**Comment by TiBarification** [comment]
This may be due to a long delay with the game server and the mysql server.
Maybe physical server with mysql has not enough free space.

**Comment by SSadistic** [comment]
I had this issue with a sqlite too, that's why I passed to MySQL, but the problem persist.

**Comment by CrazyHackGUT** [comment]
Problem also can reproduced if server can't authorize client. For example, server not authorizing any clients, if he can't connect to Steam GC Server.

**Comment by SSadistic** [comment]
I have a bot in my server (GOTV), I thought it could be "his" fault, but I doubt that.

**Comment by TiBarification** [comment]
So it was bot printing you that message?

**Comment by SSadistic** [comment]
No, it was a standard message when you type !shop, which normally opens the shop. But I have a GOTV bot in my server, which I think could be the problem, I don't know.

**Comment by SSadistic** [comment]
I removed the GOTV bot, still the same issue.

**Comment by SSadistic** [comment]
Today I change the database.cfg to:

> 	"shop"
	{
		"driver"			"sqlite"
		"database"			"_shop"
	}


A database "_shop.sq3" was created, but the same problem.

**Comment by TiBarification** [comment]
Give here result of `sm exts list`

**Comment by SSadistic** [comment]
] sm_rcon sm exts list
[SM] Displaying 19 extensions:
[01] Automatic Updater (1.8.0.6036): Updates SourceMod gamedata files
[02] Webternet (1.8.0.6036): Extension for interacting with URLs
[03] Accelerator (2.3.1): SRCDS Crash Handler
[04] CS Tools (1.8.0.6036): CS extended functionality
[05] BinTools (1.8.0.6036): Low-level C/C++ Calling API
[06] SDK Tools (1.8.0.6036): Source SDK Tools
[07] Top Menus (1.8.0.6036): Creates sorted nested menus
[08] SDK Hooks (1.8.0.6036): Source SDK Hooks
[09] REST in Pawn (1.0.2): Provides HTTP and JSON natives for plugins
[10] Client Preferences (1.8.0.6036): Saves client preference settings
[11] SQLite (1.8.0.6036): SQLite Driver
[12] Regex (1.8.0.6036): Provides regex natives for plugins
[13] GeoIP (1.8.0.6036): Geographical IP information
[14] <FAILED> file "geoipcity.ext.so": Failed to open: /home/csgo/csgomg/serverfiles/csgo/addons/sourcemod/configs/geoip/GeoIPCity.dat
[15] SteamWorks Extension (1.2.2): Exposes SteamWorks functions to Developers
[16] PTaH (P Tools and Hooks) (1.0.8): Expa

**Comment by CrazyHackGUT** [comment]
Use server console, please. `sm_rcon` truncates command output.

**Comment by SSadistic** [comment]
I don't have access to the platform, sorry.

> ] sm exts
 "Automatic Updater" (1.8.0.6036) by AlliedModders LLC: Updates SourceMod gamedata files
 "Webternet" (1.8.0.6036) by AlliedModders LLC: Extension for interacting with URLs
 "Accelerator" (2.3.1) by Asher "asherkin" Baker: SRCDS Crash Handler
 "CS Tools" (1.8.0.6036) by AlliedModders LLC: CS extended functionality
 "BinTools" (1.8.0.6036) by AlliedModders LLC: Low-level C/C++ Calling API
 "SDK Tools" (1.8.0.6036) by AlliedModders LLC: Source SDK Tools
 "Top Menus" (1.8.0.6036) by AlliedModders: Creates sorted nested menus
 "SDK Hooks" (1.8.0.6036) by AlliedModders LLC: Source SDK Hooks
 "REST in Pawn" (1.0.2) by Tsunami: Provides HTTP and JSON natives for plugins
 "Client Preferences" (1.8.0.6036) by AlliedModders: Saves client preference settings
To see more, type "sm exts 11"
] sm exts 11
 "SQLite" (1.8.0.6036) by AlliedModders LLC: SQLite Driver
 "Regex" (1.8.0.6036) by AlliedModders LLC: Provides regex natives for plugins
 "GeoIP" (1.8.0.6036) by AlliedModders LLC: Geographical IP information
 "SteamWorks Extension" (1.2.2) by Kyle Sanderson: Exposes SteamWorks functions to Developers
 "PTaH (P Tools and Hooks)" (1.0.8) by Phoenix (˙·٠●Феникс●٠·˙): Expanding sdkhooks and sdktools
 "MySQL-DBI" (1.8.0.6036) by AlliedModders LLC: MySQL driver implementation for DBI
