### ISSUE TITLE
Не работает команда sm_shop_clear_db

### ISSUE THREAD

**Issue by rsgua** [R1KO/Shop-Core#18]
Не работает команда sm_shop_clear_db и проделенное ко-во дней
После якобы очистки не чего не меняется!
Таблица shop_players не чиститься.

**Comment by TiBarification** [comment]
А вы писали после этого `sm_shop_clear_db 'ok'` ?

**Comment by rsgua** [comment]
да, написал

**Comment by TiBarification** [comment]
Напишите сюда полную последовательность действий, что вы делали командой `sm_shop_clear_db` для обнуления. Со скриншотами ответа сервера на команду в консоли.

**Comment by rsgua** [comment]
написал sm_shop_clear_db 150
и потом sm_shop_clear_db ok
сервер завис и поднялся (не крашнулся)
в базе я не увидел изменений
