### ISSUE TITLE
Новая валюта

### ISSUE THREAD

**Issue by TiBarification** [R1KO/Shop-Core#6]
Добавить новую валюту в магазин. Некоторые предметы будут доступны для покупки на новой (дополнительной) валюте. Возможна комбинация валют.

**Comment by SomethingFromSomewhere** [comment]
Это номаное нововведение.

**Comment by TiBarification** [comment]
referenced to 3aeb979

**Comment by TiBarification** [comment]
Closed due to a private edition of shop.
